/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 14 22:16:14 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      Util.indexOfNonWhitespace(charBuffer0, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Util.defaultValue("r54'jl.$nttu", "");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Util.isWhitespace('w');
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Util.isEmpty("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(14);
      Util.isEmpty(charBuffer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = Util.repeat(5196, '&');
      Util.indexOfNonWhitespace(string0, 1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Util.defaultValue((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = Util.repeatSpace('\uFFFC');
      // Undeclared exception!
      Util.rtrim(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.repeatSpace((-130));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.repeat((-1764), 'N');
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = Util.repeatSpace(5099);
      Util.ltrim(string0);
      // Undeclared exception!
      Util.ltrim(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(14);
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace(charBuffer0, (-442));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = Util.rtrim(" ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = Util.rtrim((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = Util.rtrim("r54'jl.$nttu");
      assertEquals("r54'jl.$nttu", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = Util.isWhitespace('\u000E');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = Util.ltrim((String) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = Util.ltrim(" <]gmwNJe{jc");
      assertEquals("<]gmwNJe{jc", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int int0 = Util.indexOfNonWhitespace("r54'jl.$nttu", 32);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace(" j>}o]*", (-798));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = Util.defaultValue("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = Util.repeatSpace(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = Util.repeat(0, 'M');
      assertEquals("", string0);
  }
}
