/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Nov 14 22:23:33 GMT 2025
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AmbiguousOptionException_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.AmbiguousOptionException"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "/home/dannym/projects/yorkstuff/java/eecs-4313-assignment-2-commons-cli"); 
    java.lang.System.setProperty("user.home", "/home/dannym"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dannym"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AmbiguousOptionException_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.cli.AmbiguousOptionException",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$1",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$2",
      "org.apache.commons.io.function.IOBiFunction",
      "org.apache.commons.io.file.Counters$BigIntegerCounter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.hsqldb.jdbc.JDBCDriver$1",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.function.IOSupplier",
      "org.apache.commons.io.file.Counters$Counter",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.io.IOExceptionList",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.function.IOConsumer",
      "org.apache.commons.text.similarity.SimilarityScore",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "org.apache.commons.io.file.PathFilter",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.file.Counters$NoopPathCounters",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.function.IOFunction",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.file.DeleteOption",
      "org.apache.commons.io.file.AccumulatorPathVisitor",
      "org.apache.commons.io.file.PathVisitor",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "org.apache.commons.io.file.Counters$PathCounters",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.file.NoopPathVisitor"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AmbiguousOptionException_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.cli.AmbiguousOptionException",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.AccumulatorPathVisitor",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.io.filefilter.SizeFileFilter"
    );
  }
}
