/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Nov 14 22:27:20 GMT 2025
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "/home/dannym/projects/yorkstuff/java/eecs-4313-assignment-2-commons-cli"); 
    java.lang.System.setProperty("user.home", "/home/dannym"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dannym"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "org.junitpioneer.jupiter.cartesian.CartesianArgumentsSource",
      "net.bytebuddy.description.TypeVariableSource$AbstractBase",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "net.bytebuddy.description.type.TypeList$Generic",
      "org.junitpioneer.jupiter.CartesianValueSource$CartesianValueSources",
      "org.apache.commons.io.serialization.RegexpClassNameMatcher",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.description.annotation.AnnotationList",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$EmptyEnumeration",
      "org.apache.commons.text.similarity.LevenshteinDetailedDistance",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Unresolved",
      "net.bytebuddy.description.method.MethodList",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.text.lookup.DateStringLookup",
      "org.apache.commons.text.lookup.XmlStringLookup",
      "org.apache.commons.io.serialization.ClassNameMatcher",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.apache.commons.text.similarity.EditDistance",
      "org.apache.commons.io.file.Counters$Counter",
      "net.bytebuddy.description.modifier.ModifierContributor$ForField",
      "net.bytebuddy.description.ModifierReviewable$ForFieldDescription",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.text.similarity.SimilarityScore",
      "org.junitpioneer.jupiter.CartesianEnumArgumentsProvider",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.io.file.Counters$NoopPathCounters",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.apache.commons.cli.help.TextStyle",
      "org.junitpioneer.jupiter.cartesian.CartesianTest$Values",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.description.method.MethodDescription$InDefinedShape",
      "net.bytebuddy.jar.asm.TypePath",
      "net.bytebuddy.description.type.TypeDescription$Generic$Visitor",
      "net.bytebuddy.jar.asm.MethodWriter",
      "org.apache.commons.text.similarity.SimilarityInput",
      "net.bytebuddy.jar.asm.Handle",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$ForModuleSystem",
      "net.bytebuddy.description.modifier.Ownership",
      "net.bytebuddy.jar.asm.Context",
      "net.bytebuddy.jar.asm.MethodTooLargeException",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.description.method.MethodDescription",
      "net.bytebuddy.dynamic.loading.PackageDefinitionStrategy",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "net.bytebuddy.description.type.TypeList",
      "net.bytebuddy.implementation.attribute.AnnotationValueFilter",
      "org.apache.commons.io.file.Counters$BigIntegerCounter",
      "org.apache.commons.io.function.IOBiFunction",
      "net.bytebuddy.description.type.TypeList$Generic$ForLoadedTypes",
      "org.apache.commons.text.similarity.LevenshteinResults",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "net.bytebuddy.description.modifier.ModifierContributor",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "org.apache.commons.text.similarity.IntersectionResult",
      "net.bytebuddy.description.annotation.AnnotationDescription$Loadable",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "org.apache.commons.text.similarity.IntersectionSimilarity$BagCount",
      "org.apache.commons.io.function.IOSupplier",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "net.bytebuddy.dynamic.loading.InjectionClassLoader",
      "org.apache.commons.text.lookup.ResourceBundleStringLookup",
      "net.bytebuddy.description.ModifierReviewable$AbstractBase",
      "net.bytebuddy.description.type.TypeDescription",
      "org.junitpioneer.jupiter.json.JsonClasspathSource",
      "org.apache.commons.io.FilenameUtils",
      "net.bytebuddy.jar.asm.ClassReader",
      "net.bytebuddy.implementation.bytecode.ByteCodeAppender",
      "net.bytebuddy.dynamic.loading.ClassFilePostProcessor",
      "net.bytebuddy.implementation.bytecode.StackSize",
      "org.apache.commons.text.lookup.UrlEncoderStringLookup",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "org.junitpioneer.jupiter.cartesian.CartesianParameterArgumentsProvider",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "org.apache.commons.io.function.IOFunction",
      "net.bytebuddy.utility.JavaModule$Resolver",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.junitpioneer.jupiter.CartesianAnnotationConsumer",
      "net.bytebuddy.description.type.RecordComponentList",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.description.type.TypeList$AbstractBase",
      "org.junitpioneer.jupiter.CartesianEnumSource",
      "org.junitpioneer.jupiter.cartesian.CartesianTest$MethodFactory",
      "net.bytebuddy.description.modifier.ModifierContributor$ForMethod",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DirectInvoker",
      "net.bytebuddy.description.modifier.ModifierContributor$ForParameter",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "org.junitpioneer.jupiter.json.JsonConverter",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "net.bytebuddy.description.modifier.TypeManifestation",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction",
      "org.junitpioneer.jupiter.json.Node",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForDynamicTypeHash",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.description.NamedElement$WithGenericName",
      "net.bytebuddy.implementation.HashCodeMethod",
      "org.apache.commons.text.similarity.JaccardDistance",
      "net.bytebuddy.jar.asm.SymbolTable",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "net.bytebuddy.description.type.TypeList$Generic$AbstractBase",
      "net.bytebuddy.description.modifier.SyntheticState",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.cartesian.CartesianValueArgumentsProvider",
      "org.apache.commons.io.build.AbstractSupplier",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "org.junitpioneer.jupiter.CartesianEnumSource$Mode$Validator",
      "org.hsqldb.jdbc.JDBCDriver",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader",
      "net.bytebuddy.dynamic.ClassFileLocator$Resolution",
      "net.bytebuddy.utility.Invoker",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$1",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$2",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForLegacyVm",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction$ByteArrayUrlStreamHandler",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.junitpioneer.jupiter.CartesianValueSource",
      "org.junitpioneer.jupiter.cartesian.CartesianFactoryArgumentsProvider",
      "net.bytebuddy.description.ModifierReviewable$ForMethodDescription",
      "org.hsqldb.jdbc.JDBCDriver$1",
      "net.bytebuddy.description.annotation.AnnotationValue",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "org.junitpioneer.jupiter.CartesianEnumSource$Mode",
      "net.bytebuddy.dynamic.DynamicType$Builder",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.matcher.FilterableList$Empty",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "net.bytebuddy.implementation.Implementation$Target",
      "net.bytebuddy.description.modifier.Visibility",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "net.bytebuddy.description.modifier.EnumerationState",
      "net.bytebuddy.description.type.RecordComponentList$ForLoadedRecordComponents",
      "net.bytebuddy.dynamic.ClassFileLocator",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "org.apache.commons.io.file.StandardDeleteOption",
      "net.bytebuddy.description.field.FieldList",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "net.bytebuddy.description.modifier.ModifierContributor$ForType",
      "org.apache.commons.io.FileSystem",
      "net.bytebuddy.description.type.RecordComponentList$Empty",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Defaults",
      "net.bytebuddy.utility.JavaModule",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.text.similarity.IntersectionSimilarity$TinyBag",
      "org.apache.commons.io.file.SimplePathVisitor",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "org.junitpioneer.jupiter.cartesian.ArgumentSets",
      "net.bytebuddy.jar.asm.Attribute",
      "org.apache.commons.text.StrLookup",
      "net.bytebuddy.description.type.PackageDescription",
      "org.apache.commons.io.filefilter.CanExecuteFileFilter",
      "net.bytebuddy.implementation.bytecode.StackManipulation",
      "net.bytebuddy.build.Plugin",
      "org.apache.commons.io.file.DeleteOption",
      "net.bytebuddy.description.annotation.AnnotationDescription",
      "org.apache.commons.io.file.PathVisitor",
      "org.apache.commons.text.StrLookup$ResourceBundleLookup",
      "org.apache.commons.text.similarity.IntersectionSimilarity",
      "net.bytebuddy.description.TypeVariableSource$Visitor",
      "org.apache.commons.text.lookup.UrlDecoderStringLookup",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.cli.help.TableDefinition",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForStaticTypeHash",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.description.type.TypeDescription$LazyProxy",
      "net.bytebuddy.jar.asm.Label",
      "org.apache.commons.text.similarity.CosineDistance",
      "net.bytebuddy.matcher.FilterableList",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.text.similarity.JaccardSimilarity",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SingletonEnumeration",
      "org.apache.commons.text.lookup.AbstractPathFencedLookup",
      "net.bytebuddy.description.type.TypeDescription$AbstractBase",
      "net.bytebuddy.description.type.PackageDescription$Simple",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$2",
      "net.bytebuddy.dynamic.loading.PackageDefinitionStrategy$Definition",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$1",
      "org.junitpioneer.jupiter.cartesian.CartesianMethodArgumentsProvider",
      "net.bytebuddy.jar.asm.Attribute$Set",
      "net.bytebuddy.description.ByteCodeElement$TypeDependant",
      "net.bytebuddy.jar.asm.FieldWriter",
      "org.apache.commons.text.similarity.JaroWinklerSimilarity",
      "org.apache.commons.text.lookup.UrlStringLookup",
      "org.junitpioneer.jupiter.CartesianValueArgumentsProvider",
      "net.bytebuddy.description.ModifierReviewable$ForParameterDescription",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Proxied",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.description.type.TypeDescription$Generic",
      "net.bytebuddy.jar.asm.Handler",
      "org.apache.commons.io.filefilter.FileEqualsFileFilter",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "org.mockito.internal.creation.bytebuddy.StackWalkerChecker",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "net.bytebuddy.jar.asm.Frame",
      "org.junitpioneer.jupiter.cartesian.CartesianArgumentsProvider",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.description.type.TypeDefinition",
      "org.junitpioneer.jupiter.CartesianEnumSource$CartesianEnumSources",
      "org.apache.commons.io.file.PathFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "net.bytebuddy.description.NamedElement$WithOptionalName",
      "org.apache.commons.io.IOCase",
      "net.bytebuddy.ClassFileVersion",
      "net.bytebuddy.description.type.TypeList$Empty",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.description.type.RecordComponentList$AbstractBase",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.description.ByteCodeElement",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction$ByteArrayUrlStreamHandler$ByteArrayUrlConnection",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider$Source",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.jar.asm.FieldVisitor",
      "net.bytebuddy.description.type.TypeDefinition$Sort",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.jar.asm.ClassWriter",
      "org.apache.commons.text.similarity.JaroWinklerDistance",
      "net.bytebuddy.implementation.EqualsMethod",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.bytebuddy.ClassFileVersion$VersionLocator",
      "org.apache.commons.io.file.Counters",
      "net.bytebuddy.description.type.TypeList$ForLoadedTypes",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.ConstantDynamic",
      "org.junitpioneer.jupiter.json.JsonClasspathSourceArgumentsProvider",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType",
      "net.bytebuddy.description.type.PackageDescription$AbstractBase",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.text.lookup.StringLookup",
      "net.bytebuddy.description.DeclaredByType$WithMandatoryDeclaration",
      "org.apache.commons.io.file.Counters$PathCounters",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "net.bytebuddy.matcher.FilterableList$AbstractBase",
      "net.bytebuddy.utility.GraalImageCode",
      "org.apache.commons.text.lookup.XmlEncoderStringLookup",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "org.apache.commons.text.StrLookup",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.apache.commons.text.similarity.IntersectionSimilarity",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.junitpioneer.jupiter.cartesian.CartesianValueArgumentsProvider",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.text.similarity.IntersectionSimilarity$TinyBag",
      "org.apache.commons.text.similarity.IntersectionResult",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.UrlStringLookup",
      "org.apache.commons.text.lookup.AbstractPathFencedLookup",
      "org.apache.commons.text.lookup.XmlStringLookup",
      "net.bytebuddy.dynamic.loading.InjectionClassLoader",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.ClassFileVersion",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "net.bytebuddy.jar.asm.MethodWriter",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.utility.JavaModule",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$EmptyEnumeration",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.text.lookup.XmlEncoderStringLookup",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.junitpioneer.jupiter.json.JsonClasspathSourceArgumentsProvider",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.junitpioneer.jupiter.CartesianValueArgumentsProvider",
      "org.apache.commons.text.similarity.CosineDistance",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SingletonEnumeration",
      "org.apache.commons.text.similarity.JaccardDistance",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "org.apache.commons.io.serialization.RegexpClassNameMatcher",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.text.lookup.UrlEncoderStringLookup",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "org.apache.commons.text.similarity.JaroWinklerSimilarity",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.text.lookup.DateStringLookup",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "net.bytebuddy.jar.asm.Frame",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "org.apache.commons.io.filefilter.CanExecuteFileFilter",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "org.junitpioneer.jupiter.CartesianEnumArgumentsProvider",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "org.apache.commons.io.file.Counters$NoopPathCounters",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "org.junitpioneer.jupiter.cartesian.CartesianFactoryArgumentsProvider",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction$ByteArrayUrlStreamHandler",
      "org.apache.commons.io.filefilter.FileEqualsFileFilter",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.text.similarity.JaccardSimilarity",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.text.lookup.UrlDecoderStringLookup",
      "org.apache.commons.text.similarity.LevenshteinDetailedDistance",
      "org.mockito.internal.creation.bytebuddy.StackWalkerChecker",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.text.similarity.JaroWinklerDistance",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.text.lookup.ResourceBundleStringLookup",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.cli.help.TextStyle"
    );
  }
}
