/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 14 22:00:45 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileDescriptor;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PipedOutputStream;
import java.io.PipedWriter;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.UnsupportedEncodingException;
import java.net.URISyntaxException;
import java.util.Comparator;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpFormatter_ESTest extends HelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.findWrapPos((String) null, 1427, (-2669));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FileSystemHandling.shouldAllThrowIOExceptions();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultNewLine = "";
      helpFormatter0.defaultWidth = (-1202);
      helpFormatter0.defaultArgName = "";
      helpFormatter0.defaultOptPrefix = "}=Nc\"H`<(1";
      helpFormatter0.rtrim("");
      helpFormatter0.setLongOptSeparator("BMw[pv");
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp("}=Nc\"H`<(1", options0, false);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.defaultOptPrefix = "";
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getArgName();
      helpFormatter0.getWidth();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.getOptions();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", options0);
      Options options1 = new Options();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", "#S@JHCUX:=2xOw8", options1, "#S@JHCUX:=2xOw8");
      helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator((Comparator<Option>) null);
      helpFormatter0.setOptPrefix("arg");
      helpFormatter0.getLongOptSeparator();
      MockFile mockFile0 = new MockFile("\n");
      MockFileWriter mockFileWriter0 = new MockFileWriter("arg");
      mockFileWriter0.flush();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      options0.getRequiredOptions();
      mockFile0.getAbsoluteFile();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "[", options1);
      helpFormatter0.getLongOptSeparator();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.printHelp(10, " ", (String) null, options0, "MC!_7H[72_D]pWP3");
      helpFormatter0.setLongOptSeparator("usage: ");
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix("suffix");
      Options options0 = new Options();
      helpFormatter0.printHelp("suffix", "_z_", options0, "suffix", true);
      helpFormatter0.createPadding(0);
      helpFormatter0.setLeftPadding(0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.get();
      File file0 = MockFile.createTempFile("N18Ev.Vlc~z,^kX~^(", " ", (File) null);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0);
      helpFormatter_Builder0.setPrintWriter(mockPrintWriter1);
      helpFormatter0.getWidth();
      mockPrintWriter1.append((CharSequence) "_z_");
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 3, "_Xj#WX)M1Xe!PV", "\n", options0, 74, 0, "org.apache.commons.cli.HelpFormatter$1", true);
      // Undeclared exception!
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 1, "--", "", options0, (-3310), 3, "arg", true);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.getOptions();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", options0);
      Options options1 = new Options();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", "#S@JHCUX:=2xOw8", options1, "#S@JHCUX:=2xOw8");
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.setOptPrefix("arg");
      helpFormatter0.getLongOptSeparator();
      MockFile mockFile0 = new MockFile("\n");
      options1.addOption("Options", "arg", true, "arg");
      MockFileWriter mockFileWriter0 = new MockFileWriter("arg");
      mockFileWriter0.flush();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      mockFile0.getAbsoluteFile();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "[", options1);
      helpFormatter0.getLongOptSeparator();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.printHelp(10, " ", (String) null, options0, "MC!_7H[72_D]pWP3");
      helpFormatter0.setLongOptSeparator("usage: ");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.getOptions();
      options0.getOptions();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", options0);
      Options options1 = new Options();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", "#S@JHCUX:=2xOw8", options1, "#S@JHCUX:=2xOw8");
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.setOptPrefix("+");
      helpFormatter0.getLongOptSeparator();
      MockFile mockFile0 = new MockFile("\n");
      MockFileWriter mockFileWriter0 = new MockFileWriter(mockFile0, true);
      mockFileWriter0.flush();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      mockFile0.getAbsoluteFile();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "[", options1);
      helpFormatter0.getLongOptSeparator();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.printHelp(10, " ", (String) null, options0, "MC!_7H[72_D]pWP3");
      helpFormatter0.setLongOptSeparator((String) null);
      helpFormatter0.getSyntaxPrefix();
      helpFormatter0.findWrapPos("MC!_7H[72_D]pWP3", 0, 15);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      helpFormatter0.getLongOptPrefix();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("qJF");
      mockPrintWriter0.println(3079);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, (-1972), "qJF", "", (Options) null, (-1972), (-1972), "qJF", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix("suffix");
      Options options0 = new Options();
      helpFormatter0.printHelp("suffix", "_z_", options0, "suffix", true);
      helpFormatter0.setLeftPadding(0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.get();
      File file0 = MockFile.createTempFile("N18Ev.Vlc~z,^kX~^(", " ", (File) null);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0);
      helpFormatter_Builder0.setPrintWriter(mockPrintWriter1);
      helpFormatter0.getWidth();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 3, "_Xj#WX)M1Xe!PV", "\n", options0, 74, (-10), "org.apache.commons.cli.HelpFormatter$1", true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      StringWriter stringWriter0 = new StringWriter(74);
      stringWriter0.append((CharSequence) "-");
      BufferedWriter bufferedWriter0 = new BufferedWriter(stringWriter0, 45);
      bufferedWriter0.close();
      Options options0 = new Options();
      helpFormatter0.appendOptions(bufferedWriter0, 45, options0, 45, 45);
      helpFormatter0.getSyntaxPrefix();
      helpFormatter0.getDescPadding();
      helpFormatter0.appendOptions((CharArrayWriter) null, 3, options0, 45, 31);
      HelpFormatter helpFormatter1 = new HelpFormatter();
      options0.toString();
      StringBuffer stringBuffer0 = new StringBuffer(" [stringLookupMap=");
      stringBuffer0.insert(1, (-524L));
      Options options1 = new Options();
      helpFormatter_Builder0.setShowSince(false);
      options0.addOptions(options1);
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      StringBuffer stringBuffer1 = helpFormatter1.renderOptions(stringBuffer0, 31, options0, 335, 3);
      helpFormatter0.appendWrappedText(stringBuffer1, 45, (-2958), "usage: ");
      helpFormatter1.getLeftPadding();
      HelpFormatter.builder();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      PrintWriter printWriter0 = null;
      int int0 = 0;
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 1085, "", "jcT.", options0, 0, 1085, "Since");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      Options options0 = new Options();
      options0.getOptions();
      options0.getOptions();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", options0);
      Options options1 = new Options();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", "#S@JHCUX:=2xOw8", options1, "#S@JHCUX:=2xOw8");
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.setOptPrefix("+");
      helpFormatter0.getLongOptSeparator();
      MockFile mockFile0 = new MockFile("\n");
      MockFileWriter mockFileWriter0 = new MockFileWriter(mockFile0, true);
      mockFileWriter0.flush();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      mockFile0.getAbsoluteFile();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "[", options1);
      helpFormatter0.getLongOptSeparator();
      Function<Option, String> function1 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function1);
      helpFormatter0.printHelp(10, " ", (String) null, options0, "MC!_7H[72_D]pWP3");
      helpFormatter0.setLongOptSeparator((String) null);
      Option option0 = new Option("directoryFilter", "JD4a4", true, (String) null);
      HelpFormatter.getDescription(option0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      int int0 = (-1076);
      // Undeclared exception!
      try { 
        helpFormatter0.printUsage((PrintWriter) null, (-1076), ":|\"S?/");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFile mockFile0 = new MockFile("--");
      File file0 = MockFile.createTempFile("arg", "usage: ", (File) mockFile0);
      MockPrintStream mockPrintStream0 = new MockPrintStream(file0);
      mockFile0.getAbsoluteFile();
      Object[] objectArray0 = new Object[8];
      objectArray0[0] = (Object) helpFormatter0;
      Object object0 = new Object();
      objectArray0[1] = object0;
      Object object1 = new Object();
      objectArray0[2] = object1;
      objectArray0[3] = (Object) mockPrintStream0;
      objectArray0[4] = (Object) file0;
      objectArray0[5] = (Object) null;
      objectArray0[6] = (Object) mockFile0;
      objectArray0[7] = (Object) file0;
      mockPrintStream0.format((Locale) null, "ewBVu?x*", objectArray0);
      mockPrintStream0.print(false);
      MockFileWriter mockFileWriter0 = new MockFileWriter(file0, false);
      Object[] objectArray1 = new Object[6];
      objectArray1[0] = (Object) mockFile0;
      objectArray1[1] = (Object) mockFile0;
      objectArray1[2] = (Object) helpFormatter0;
      objectArray1[3] = (Object) helpFormatter0;
      objectArray1[4] = (Object) "usage: ";
      objectArray1[5] = (Object) mockPrintStream0;
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.appendOptions(mockPrintStream0, 0, (Options) null, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFile mockFile0 = new MockFile("--");
      mockFile0.getAbsoluteFile();
      MockFileWriter mockFileWriter0 = new MockFileWriter(mockFile0, false);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) mockFile0;
      objectArray0[2] = (Object) helpFormatter0;
      objectArray0[3] = (Object) helpFormatter0;
      objectArray0[4] = (Object) "";
      String string0 = "<";
      helpFormatter0.createPadding(0);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(3);
      CharArrayWriter charArrayWriter1 = charArrayWriter0.append('N');
      CharArrayWriter charArrayWriter2 = charArrayWriter1.append((CharSequence) "");
      helpFormatter0.appendWrappedText(charArrayWriter2, 0, 0, " ");
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(0, "=f8A/IM hPtGF5S", "=f8A/IM hPtGF5S", (Options) null, "<");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.setLeftPadding(0);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(pipedOutputStream0);
      Object[] objectArray0 = new Object[1];
      options0.getMatchingOptions("@l/b#/ =57");
      objectArray0[0] = (Object) options0;
      PrintWriter printWriter0 = mockPrintWriter0.format("-", objectArray0);
      helpFormatter0.printUsage(printWriter0, 0, "-", options0);
      helpFormatter0.getLeftPadding();
      helpFormatter0.printHelp(printWriter0, 0, "A", "@l/b#/ =57", options0, 0, 0, "arg");
      helpFormatter0.printOptions(mockPrintWriter0, 0, options0, 0, 20);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      helpFormatter_Builder2.setPrintWriter(printWriter0);
      helpFormatter0.printHelp(0, "-", "A", options0, "A", true);
      helpFormatter0.setLongOptPrefix("org.apache.commons.cli.HelpFormatter$1");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setOptionComparator((Comparator<Option>) null);
      MockFile mockFile0 = new MockFile("usage: ", "-");
      helpFormatter0.getOptionComparator();
      helpFormatter0.getLeftPadding();
      MockFile mockFile1 = new MockFile(mockFile0, "J_^X:~F]fP.YQY");
      String string0 = "o";
      MockPrintWriter mockPrintWriter0 = null;
      try {
        mockPrintWriter0 = new MockPrintWriter(mockFile1, "o");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // o
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FileSystemHandling.appendStringToFile((EvoSuiteFile) null, "");
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.findWrapPos("", 3, (-928));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix("suffix");
      Options options0 = new Options();
      helpFormatter0.printHelp("suffix", "_z_", options0, "suffix", true);
      helpFormatter0.createPadding(0);
      helpFormatter0.setLeftPadding(0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.get();
      File file0 = MockFile.createTempFile("N18Ev.Vlc~z,^kX~^(", " ", (File) null);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0);
      helpFormatter_Builder0.setPrintWriter(mockPrintWriter1);
      helpFormatter0.getWidth();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 3, "_Xj#WX)M1Xe!PV", "\n", options0, 74, 0, "org.apache.commons.cli.HelpFormatter$1", true);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer(" ");
      Options options0 = new Options();
      options0.getOptionGroups();
      stringBuffer0.trimToSize();
      helpFormatter0.renderOptions(stringBuffer0, (-57), options0, 16, 0);
      helpFormatter0.getArgName();
      helpFormatter0.setWidth(0);
      helpFormatter0.setLongOptSeparator("arg");
      helpFormatter0.setWidth(16);
      StringBuilder stringBuilder0 = new StringBuilder("org.apache.commons.text.lookup.PropertiesStringLookup");
      HelpFormatter.builder();
      helpFormatter0.rtrim((String) null);
      HelpFormatter.builder();
      StringBuilder stringBuilder1 = stringBuilder0.insert(0, '>');
      StringBuilder stringBuilder2 = stringBuilder1.append(true);
      stringBuilder2.insert(16, true);
      helpFormatter0.setDescPadding(1815);
      MockFile mockFile0 = new MockFile("", "F>b");
      MockFileWriter mockFileWriter0 = new MockFileWriter(mockFile0);
      // Undeclared exception!
      try { 
        helpFormatter0.appendOptions((OutputStreamWriter) mockFileWriter0, 4, options0, 752, (-1101));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      PipedWriter pipedWriter0 = new PipedWriter();
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      int int0 = 13;
      String string0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.appendWrappedText(pipedWriter0, 13, 13, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("-");
      Options options0 = new Options();
      // Undeclared exception!
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 1, "%Vpd[9d|FD6IMg!LRA0", "%Vpd[9d|FD6IMg!LRA0", options0, 1, 1543, "%Vpd[9d|FD6IMg!LRA0");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultNewLine = "";
      helpFormatter0.defaultWidth = (-1202);
      helpFormatter0.defaultArgName = "";
      helpFormatter0.defaultOptPrefix = "}=Nc\"H`<(1";
      helpFormatter0.rtrim("");
      helpFormatter0.setLongOptSeparator("BMw[pv");
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      options0.addOption((String) null, false, "--");
      helpFormatter0.printHelp("}=Nc\"H`<(1", options0, false);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.getLongOptSeparator();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(charArrayWriter0, false);
      Options options1 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(mockPrintWriter0, 1339224004, options1, (-1202), (-1202));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultLeftPad = (-1255);
      int int0 = 87;
      helpFormatter0.defaultDescPad = 87;
      int int1 = (-1);
      helpFormatter0.setLeftPadding((-1));
      String string0 = "\\V,2b5*Hx";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("V,2b5*Hx", "V,2b5*Hx", options0, "V,2b5*Hx");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringWriter stringWriter0 = new StringWriter(1);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      helpFormatter0.appendWrappedText(stringBuffer0, 90, 90, "=UP$+,6?0o=X4");
      helpFormatter0.getOptionComparator();
      PipedWriter pipedWriter0 = new PipedWriter();
      try { 
        helpFormatter0.appendWrappedText(pipedWriter0, 90, 2719, ",NW:P ucgO<8!pr");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.rtrim("");
      helpFormatter0.appendWrappedText((PipedWriter) null, (-3213), (-352), "rES;\u0005iOlPO= -n.>");
      Options options0 = new Options();
      options0.getOption("[Deprecated] ");
      helpFormatter0.getNewLine();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFile mockFile0 = new MockFile("--");
      File file0 = MockFile.createTempFile("arg", "usage: ", (File) mockFile0);
      MockPrintStream mockPrintStream0 = new MockPrintStream(file0);
      mockFile0.getAbsoluteFile();
      int int0 = 0;
      mockPrintStream0.print(false);
      MockFileWriter mockFileWriter0 = new MockFileWriter(file0, false);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, false);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) mockFile0;
      objectArray0[1] = (Object) mockFile0;
      objectArray0[2] = (Object) helpFormatter0;
      objectArray0[3] = (Object) helpFormatter0;
      objectArray0[4] = (Object) "";
      objectArray0[5] = (Object) mockPrintStream0;
      PrintWriter printWriter0 = mockPrintWriter0.printf("", objectArray0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(printWriter0, 0, "", "", (Options) null, 0, 0, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer(74);
      Options options0 = new Options();
      options0.hasOption("-");
      helpFormatter0.renderOptions(stringBuffer0, 0, options0, 1170, 0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      helpFormatter1.defaultSyntaxPrefix = "usage: ";
      helpFormatter0.setDescPadding(0);
      helpFormatter0.defaultLongOptPrefix = "?ZfO2u";
      Options options1 = new Options();
      // Undeclared exception!
      helpFormatter0.printHelp(1, " ", "Rj'", options1, "a@:i[91|&P@D", false);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      HelpFormatter helpFormatter1 = new HelpFormatter();
      Comparator<Option> comparator0 = helpFormatter1.optionComparator;
      helpFormatter0.setOptionComparator(comparator0);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(function0);
      Function<Option, String> function1 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder3.setShowDeprecated(function1);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("-");
      helpFormatter_Builder3.setPrintWriter(mockPrintWriter0);
      HelpFormatter.Builder helpFormatter_Builder4 = helpFormatter_Builder3.setPrintWriter(mockPrintWriter0);
      Function<Option, String> function2 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder4.setShowDeprecated(function2);
      StringWriter stringWriter0 = new StringWriter(3);
      StringWriter stringWriter1 = stringWriter0.append('%');
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      Options options0 = new Options();
      int int0 = 1;
      helpFormatter0.renderOptions(stringBuffer0, 1, options0, 1, 1);
      helpFormatter1.setNewLine("-");
      helpFormatter1.getDescPadding();
      // Undeclared exception!
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 1, "usage: ", options0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFile mockFile0 = new MockFile("$;^eZ3/vq$0u[:4.8`", "<");
      MockFile mockFile1 = new MockFile(mockFile0, "usage: ");
      File file0 = MockFile.createTempFile("arg", "--", (File) mockFile1);
      mockFile0.getCanonicalFile();
      mockFile1.setExecutable(false, false);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, " | ");
      helpFormatter0.rtrim("8=q`:8*MW'/");
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      PipedWriter pipedWriter0 = new PipedWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(pipedWriter0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setPrintWriter(mockPrintWriter0);
      Locale locale0 = Locale.ROOT;
      Object[] objectArray0 = new Object[8];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) pipedWriter0;
      objectArray0[2] = (Object) helpFormatter_Builder0;
      objectArray0[3] = (Object) mockPrintWriter0;
      objectArray0[4] = (Object) helpFormatter_Builder2;
      objectArray0[5] = (Object) function0;
      objectArray0[6] = (Object) pipedWriter0;
      objectArray0[7] = (Object) locale0;
      mockPrintWriter0.format(locale0, "", objectArray0);
      helpFormatter_Builder0.get();
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      Options options0 = new Options();
      helpFormatter0.renderOptions((StringBuffer) null, 0, options0, 0, 0);
      Option option0 = null;
      try {
        option0 = new Option("-", true, "usage: ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '-'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("lm/r", "lm/r", options0, "lm/r");
      helpFormatter0.setLongOptSeparator(" ]");
      helpFormatter0.setLongOptSeparator("");
      options0.getRequiredOptions();
      options0.hasLongOption("-");
      Option option0 = new Option("arg", "");
      options0.addOption(option0);
      HelpFormatter.builder();
      helpFormatter0.setOptPrefix("");
      helpFormatter0.printHelp("[", "lm/r", options0, "", false);
      helpFormatter0.getOptionComparator();
      helpFormatter0.getOptPrefix();
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[7];
      charArray0[0] = ':';
      charArray0[1] = 'v';
      charArray0[2] = '';
      charArray0[3] = 'W';
      charArray0[4] = '#';
      charArray0[5] = '.';
      charArray0[6] = 'G';
      stringWriter0.write(charArray0);
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) "usage: ");
      helpFormatter0.appendWrappedText(stringWriter1, (-2), (-2), "");
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      int int0 = 3;
      StringWriter stringWriter0 = new StringWriter(3);
      StringWriter stringWriter1 = stringWriter0.append('n');
      stringWriter0.write("");
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      // Undeclared exception!
      try { 
        helpFormatter0.renderOptions(stringBuffer0, 3, (Options) null, 3, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.getLongOptSeparator();
      Options options0 = new Options();
      options0.toString();
      helpFormatter0.setArgName(" ");
      boolean boolean0 = false;
      helpFormatter0.printHelp(" ", options0, false);
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      PrintWriter printWriter0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 0, "[ Options: [ short {} ] [ long {} ]", "IfjnBKh)=3", options0, 0, 138, "[ Options: [ short {} ] [ long {} ]", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(13, "-", "'V", (Options) null, "-", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(false);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(false);
      MockPrintStream mockPrintStream0 = new MockPrintStream("org.apache.commons.text.StrLookup$ResourceBundleLookup");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0, false);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setPrintWriter(mockPrintWriter0);
      mockPrintWriter0.print(false);
      mockPrintWriter0.println(1014.594468267455);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = null;
      helpFormatter_Builder3.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(35, "org.apache.commons.text.StrLookup$ResourceBundleLookup", "", (Options) null, "org.apache.commons.text.StrLookup$ResourceBundleLookup", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      int int0 = 0;
      helpFormatter0.setWidth(0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      String string0 = "vDfL";
      helpFormatter_Builder0.setShowDeprecated(true);
      boolean boolean0 = true;
      helpFormatter_Builder1.setShowDeprecated(true);
      Options options0 = new Options();
      helpFormatter_Builder0.setShowDeprecated(false);
      helpFormatter0.printHelp(74, "vDfL", "l", options0, "vDfL");
      helpFormatter0.getOptPrefix();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder1.setShowDeprecated(function0);
      Option option0 = new Option("arg", false, "");
      HelpFormatter.getDescription(option0);
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.setDescPadding(3569);
      helpFormatter0.setLeftPadding((-1));
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getDescPadding();
      helpFormatter0.setLongOptSeparator("#");
      helpFormatter0.setNewLine(" ");
      String string1 = null;
      MockFile mockFile0 = null;
      try {
        mockFile0 = new MockFile("file", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((PrintWriter) null, 0, options0, 0, 224);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      helpFormatter_Builder0.setShowSince(true);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(function0);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      boolean boolean0 = false;
      helpFormatter_Builder3.setShowSince(false);
      int int0 = 9;
      helpFormatter0.setDescPadding(9);
      helpFormatter0.getLeftPadding();
      String string0 = "\"Hg\\lp1M|";
      helpFormatter0.defaultSyntaxPrefix = "\"Hglp1M|";
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("\"Hglp1M|", "\"Hglp1M|", (Options) null, "\"Hglp1M|", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Comparator<Option> comparator0 = helpFormatter0.optionComparator;
      helpFormatter0.optionComparator = comparator0;
      helpFormatter0.setSyntaxPrefix(",nd");
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(",nd", "\"X%.uK)", (Options) null, "\"X%.uK)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 2425, "D:]4~opd", "D:]4~opd", options0, 2425, Integer.MAX_VALUE, "D:]4~opd", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter.builder();
      int int0 = 0;
      Options options0 = new Options();
      String string0 = "OVERRIDE_READ_ONLY";
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((-2628), "", "", options0, "OVERRIDE_READ_ONLY");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("sun.cpu.isalist");
      Options options0 = new Options();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, (-220), " ", "k6nC[{Kd3,Z", options0, 0, 32, "", true);
      helpFormatter0.setLeftPadding(0);
      helpFormatter0.getWidth();
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix("Duplicate key: ");
      int int0 = 0;
      helpFormatter0.renderWrappedText((StringBuffer) null, 0, 0, "");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      int int1 = (-1);
      BufferedOutputStream bufferedOutputStream0 = null;
      try {
        bufferedOutputStream0 = new BufferedOutputStream(byteArrayOutputStream0, (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Buffer size <= 0
         //
         verifyException("java.io.BufferedOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.getArgName();
      helpFormatter0.setNewLine("m:$7<[=");
      helpFormatter0.setNewLine("arg");
      helpFormatter0.setWidth((-2468));
      helpFormatter0.getNewLine();
      helpFormatter0.setWidth((-2468));
      helpFormatter0.setLongOptPrefix("");
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "usage: ", (Options) null, "YZRuQ+6b");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptSeparator("Npp{YL{KC/E2fIR");
      StringBuffer stringBuffer0 = new StringBuffer();
      StringBuffer stringBuffer1 = helpFormatter0.renderWrappedText(stringBuffer0, 4, 4, "Npp{YL{KC/E2fIR");
      String string0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.renderWrappedText(stringBuffer1, 4, 4, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(true);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("h", "", options0, (String) null, true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = "?^s+-Vm%t~~";
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("?^s+-Vm%t~~");
      Options options0 = new Options();
      mockPrintWriter0.checkError();
      helpFormatter_Builder0.setShowDeprecated(false);
      int int0 = (-723);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 0, "?^s+-Vm%t~~", "?^s+-Vm%t~~", options0, 0, (-723), "?^s+-Vm%t~~");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.createPadding(2202);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      int int0 = 4346;
      helpFormatter0.setDescPadding(4346);
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("walk", (Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("-");
      int int0 = 0;
      Options options0 = new Options();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 0, "%Vpd[9d|FD6IMg!LRA0", "%Vpd[9d|FD6IMg!LRA0", options0, 0, 1543, "%Vpd[9d|FD6IMg!LRA0");
      options0.getMatchingOptions("arg");
      int int1 = (-3199);
      mockPrintWriter0.println();
      helpFormatter0.defaultLeftPad = 0;
      String string0 = "";
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "org.apache.commons.io.serialization.FullClassNameMatcher", options0, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setDescPadding(0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder2.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      helpFormatter_Builder2.get();
      helpFormatter_Builder1.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("m]J{w*>vf@=mj", options0, true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      helpFormatter_Builder0.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(116909544, "", (String) null, options0, (String) null, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp("-", "-", options0, "-", false);
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "arg");
      StringBuffer stringBuffer1 = helpFormatter0.renderOptions(stringBuffer0, 10, options0, 10, 10);
      StringBuffer stringBuffer2 = helpFormatter0.renderWrappedText(stringBuffer1, 10, (-991), "-");
      helpFormatter0.renderOptions(stringBuffer2, 620, options0, 134, 1);
      String string0 = "";
      String string1 = "";
      try { 
        MockURI.URI("usage: ", "usage: ", "arg");
        fail("Expecting exception: URISyntaxException");
      
      } catch(URISyntaxException e) {
         //
         // Illegal character in opaque part at index 6: usage: :usage:%20#arg
         //
         verifyException("java.net.URI$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.getLeftPadding();
      helpFormatter0.getLongOptPrefix();
      String string0 = "VL4JNY;";
      int int0 = 0;
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      CharArrayWriter charArrayWriter1 = charArrayWriter0.append('j');
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.appendOptions(charArrayWriter1, (-3189), options0, (-688), 0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setNewLine("bcE#ndY<~4g");
      Options options0 = new Options();
      helpFormatter0.printHelp("bcE#ndY<~4g", "Since", options0, "-", true);
      helpFormatter0.findWrapPos("bcE#ndY<~4g", (-2391), 1139);
      helpFormatter0.getLongOptPrefix();
      options0.hasLongOption((String) null);
      HelpFormatter.builder();
      helpFormatter0.getNewLine();
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(true);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(charArrayWriter0, true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setPrintWriter(mockPrintWriter0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      helpFormatter_Builder3.get();
      charArrayWriter0.append((CharSequence) "--");
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 2580, "org.apache.commons.io.filefilter.HiddenFileFilter", options0);
      HelpFormatter.Builder helpFormatter_Builder4 = helpFormatter_Builder0.setShowDeprecated(false);
      helpFormatter0.printWrapped((PrintWriter) mockPrintWriter0, (-4410), 3767, "org.apache.commons.io.filefilter.HiddenFileFilter");
      helpFormatter1.printWrapped((PrintWriter) mockPrintWriter0, 2580, "--");
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 3, "--", options0);
      helpFormatter_Builder4.setShowSince(true);
      helpFormatter0.appendWrappedText(charArrayWriter0, (-4410), 1, "--");
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.createPadding((-991));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setOptPrefix("");
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      // Undeclared exception!
      try { 
        helpFormatter0.printWrapped((PrintWriter) null, 2063, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      boolean boolean0 = false;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(function0);
      File file0 = MockFile.createTempFile("[Deprecated] ", "[Deprecated] ");
      MockPrintStream mockPrintStream0 = new MockPrintStream(file0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0, true);
      Object[] objectArray0 = new Object[4];
      objectArray0[0] = (Object) function0;
      Object object0 = new Object();
      objectArray0[1] = object0;
      objectArray0[2] = (Object) helpFormatter_Builder2;
      objectArray0[3] = (Object) mockPrintStream0;
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      PrintWriter printWriter0 = mockPrintWriter0.printf("[Deprecated] ", objectArray0);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setPrintWriter(printWriter0);
      HelpFormatter.Builder helpFormatter_Builder4 = helpFormatter_Builder3.setShowDeprecated(false);
      HelpFormatter helpFormatter1 = helpFormatter_Builder4.get();
      int int0 = 0;
      helpFormatter1.createPadding(0);
      helpFormatter0.setLongOptPrefix(" ");
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 0, "\n", "\n", (Options) null, 3, 74, "--");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      StringWriter stringWriter0 = new StringWriter(2373);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter0);
      PrintWriter printWriter0 = mockPrintWriter0.append('#');
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setPrintWriter(printWriter0);
      helpFormatter_Builder1.setPrintWriter(printWriter0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      // Undeclared exception!
      try { 
        helpFormatter_Builder0.setPrintWriter((PrintWriter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // printWriter
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 2276, "60=^KC6^0=!LkX2Jg", "", options0, (-4243), (-2341), "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getWidth();
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
          HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
          helpFormatter0.getSyntaxPrefix();
          helpFormatter0.getOptionComparator();
          FileDescriptor fileDescriptor0 = new FileDescriptor();
          MockFileWriter mockFileWriter0 = null;
          try {
            mockFileWriter0 = new MockFileWriter(fileDescriptor0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.lang.RuntimePermission\" \"writeFileDescriptor\")
             // java.lang.Thread.getStackTrace(Thread.java:1564)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkWrite(SecurityManager.java:954)
             // java.io.FileOutputStream.<init>(FileOutputStream.java:245)
             // java.io.FileWriter.<init>(FileWriter.java:116)
             // org.evosuite.runtime.mock.java.io.MockFileWriter.<init>(MockFileWriter.java:79)
             // sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
             // sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
             // sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             // java.lang.reflect.Constructor.newInstance(Constructor.java:423)
             // org.evosuite.testcase.statements.ConstructorStatement$1.execute(ConstructorStatement.java:233)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.ConstructorStatement.execute(ConstructorStatement.java:188)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:750)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", options0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("EEE MMM dd HH:mm:ss zzz yyyy", options0);
      Options options1 = new Options();
      options1.toString();
      helpFormatter0.setLongOptPrefix("cmdLineSyntax not provided");
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "s", options1, "s", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(3);
      MockPrintStream mockPrintStream0 = new MockPrintStream(byteArrayOutputStream0);
      PrintStream printStream0 = mockPrintStream0.append((CharSequence) "arg", 1, 1);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(printStream0);
      Object[] objectArray0 = new Object[4];
      objectArray0[0] = (Object) mockPrintStream0;
      objectArray0[1] = (Object) printStream0;
      objectArray0[2] = (Object) mockPrintWriter0;
      objectArray0[3] = (Object) mockPrintWriter0;
      PrintWriter printWriter0 = mockPrintWriter0.format("arg", objectArray0);
      String string0 = "o!Z5dY|xzAKt]O1~F0&";
      Options options0 = new Options();
      helpFormatter0.printUsage(printWriter0, 0, "o!Z5dY|xzAKt]O1~F0&", options0);
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter0.getOptionComparator();
      MockPrintWriter mockPrintWriter1 = null;
      try {
        mockPrintWriter1 = new MockPrintWriter("", "");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // 
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(true);
      Function<Option, String> function0 = null;
      helpFormatter_Builder1.setShowDeprecated((Function<Option, String>) null);
      MockPrintWriter mockPrintWriter0 = null;
      try {
        mockPrintWriter0 = new MockPrintWriter("", "gY l!2");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // gY l!2
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      String string1 = "A";
      Options options0 = new Options();
      int int0 = 0;
      helpFormatter0.setLeftPadding(0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "A", options0, "A", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      // Undeclared exception!
      try { 
        HelpFormatter.getDescription((Option) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.get();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      int int0 = 0;
      Options options0 = new Options();
      HelpFormatter.builder();
      helpFormatter0.printHelp(0, "%b;E?-qD!;(1#5y", "%b;E?-qD!;(1#5y", options0, "%b;E?-qD!;(1#5y");
      String string0 = "";
      Options options1 = new Options();
      PrintWriter printWriter0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printWrapped((PrintWriter) null, (-403), 35, "i:D");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("E'?\"", "-", options0, "E'?\"");
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "--");
      StringBuffer stringBuffer1 = helpFormatter0.renderWrappedText(stringBuffer0, (-1375), (-1375), "-");
      Options options1 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.renderOptions(stringBuffer1, 901, options1, 0, (-1375));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Option option0 = new Option("Description", "Description");
      HelpFormatter.getDescription(option0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setLongOptSeparator("java/util/function/Function");
      helpFormatter_Builder0.setShowSince(true);
      helpFormatter0.findWrapPos("java/util/function/Function", 0, 0);
      Options options0 = new Options();
      options0.hasShortOption("");
      helpFormatter0.printHelp("java/util/function/Function", options0, true);
      helpFormatter0.setSyntaxPrefix("java/util/function/Function");
      helpFormatter0.getArgName();
      helpFormatter0.setWidth(0);
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter0.printHelp((-399), "java/util/function/Function", "", options0, "");
      helpFormatter0.setLongOptSeparator("org.apache.commons.cli.HelpFormatter$OptionComparator");
      helpFormatter_Builder0.setShowSince(false);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultLeftPad = (-1255);
      int int0 = 87;
      helpFormatter0.defaultDescPad = 87;
      int int1 = (-1);
      helpFormatter0.setLeftPadding((-1));
      String string0 = "\\V,2b5*Hx";
      Options options0 = new Options();
      options0.hasOption("arg");
      // Undeclared exception!
      helpFormatter0.printHelp(1, "V,2b5*Hx", "V,2b5*Hx", options0, "V,2b5*Hx");
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.rtrim("");
      Options options0 = new Options();
      options0.getOption("[Deprecated] ");
      helpFormatter0.printHelp((-3213), "rES;\u0005iOlPO= -n.>", "f5", options0, "rES;\u0005iOlPO= -n.>", true);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.setShowDeprecated(false);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("pathMatcher", "nL@", options0, (String) null, true);
      helpFormatter0.defaultLeftPad = 3281;
      helpFormatter0.setWidth(351608024);
      helpFormatter0.getOptionComparator();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("nL@", (Options) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "cD'aS666.", options0, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      int int0 = 3082;
      helpFormatter0.setWidth(3082);
      helpFormatter0.getDescPadding();
      Comparator<Option> comparator0 = helpFormatter0.optionComparator;
      helpFormatter0.optionComparator = comparator0;
      helpFormatter0.findWrapPos("", (-1969), 3);
      helpFormatter0.setArgName("");
      helpFormatter0.setWidth((-1966));
      File file0 = MockFile.createTempFile("before", "RegexFileFilter [pattern=");
      MockPrintWriter mockPrintWriter0 = null;
      try {
        mockPrintWriter0 = new MockPrintWriter(file0, "|=0");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // |=0
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setLeftPadding(3);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      options0.getOptionGroups();
      options0.hasShortOption("usage: ");
      options0.getOptionGroups();
      helpFormatter0.printHelp("-", "-", options0, "org.apache.commons.io.file.Counters$NoopCounter");
      helpFormatter0.printHelp("org.apache.commons.io.file.Counters$NoopCounter", options0, true);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp(457, "org.apache.commons.io.build.AbstractSupplier", (String) null, options0, "C", false);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", options0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultNewLine = "org.apache.commons.cli.DeprecatedAttributes";
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      Options options0 = new Options();
      helpFormatter0.appendOptions(charArrayWriter0, 4140, options0, 0, 0);
      helpFormatter0.rtrim("&k+CqUnS");
      helpFormatter0.rtrim("<");
      helpFormatter0.setSyntaxPrefix("<");
      helpFormatter0.getArgName();
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      StringBuffer stringBuffer0 = new StringBuffer();
      StringBuffer stringBuffer1 = helpFormatter0.renderWrappedText(stringBuffer0, 44, 44, "");
      helpFormatter0.renderWrappedText(stringBuffer1, 44, 0, "{xRig+vVY.Xme\"");
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printUsage((PrintWriter) null, 3, "TLiR#MAXGt%6sP", options0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockPrintStream mockPrintStream0 = new MockPrintStream("-");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0, false);
      Options options0 = new Options();
      helpFormatter0.printOptions(mockPrintWriter0, 10, options0, 1788, 10);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getOptPrefix();
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setWidth(0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      helpFormatter_Builder0.setShowDeprecated(true);
      helpFormatter_Builder1.setShowDeprecated(true);
      Options options0 = new Options();
      helpFormatter_Builder0.setShowDeprecated(false);
      helpFormatter0.printHelp(74, "vDfL", "-", options0, "vDfL");
      helpFormatter0.getOptPrefix();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder1.setShowDeprecated(function0);
      Option option0 = new Option("arg", false, "");
      HelpFormatter.getDescription(option0);
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.setDescPadding(3569);
      helpFormatter0.setLeftPadding((-1));
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getDescPadding();
      helpFormatter0.setLongOptSeparator("#");
      helpFormatter0.setNewLine(" ");
      MockFile mockFile0 = null;
      try {
        mockFile0 = new MockFile("file", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((PrintWriter) null, 0, options0, 0, 224);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Options options0 = new Options();
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.getOptions();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", options0);
      Options options1 = new Options();
      helpFormatter0.printHelp("#S@JHCUX:=2xOw8", "#S@JHCUX:=2xOw8", options1, "#S@JHCUX:=2xOw8");
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.setOptPrefix("arg");
      helpFormatter0.getLongOptSeparator();
      MockFile mockFile0 = new MockFile("\n");
      options1.addOption("Options", "arg", true, "arg");
      MockFileWriter mockFileWriter0 = new MockFileWriter("arg");
      mockFileWriter0.flush();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      mockFile0.getAbsoluteFile();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "[", options1);
      helpFormatter0.getLongOptSeparator();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = new HelpFormatter.Builder();
      helpFormatter0.printHelp(10, " ", (String) null, options0, "MC!_7H[72_D]pWP3");
      helpFormatter0.setLongOptSeparator("usage: ");
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) null;
      objectArray0[1] = (Object) helpFormatter0;
      objectArray0[2] = (Object) helpFormatter0;
      PrintWriter printWriter0 = mockPrintWriter0.format("I0}lWD6Zo@uqZN2", objectArray0);
      helpFormatter0.printOptions(printWriter0, 10, options1, 35, 99);
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix("suffix");
      Options options0 = new Options();
      helpFormatter0.printHelp("suffix", "_z_", options0, "suffix", true);
      helpFormatter0.createPadding(0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter1 = new HelpFormatter();
      File file0 = MockFile.createTempFile("N18Ev.Vlc~z,^kX~^(", " ", (File) null);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0);
      helpFormatter_Builder0.setPrintWriter(mockPrintWriter1);
      helpFormatter0.getWidth();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 3, "-", "\n", options0, 74, 0, "org.apache.commons.cli.HelpFormatter$1", true);
      helpFormatter0.getLeftPadding();
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) " ");
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      helpFormatter0.renderWrappedText(stringBuffer0, 2276, (-951), "(");
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 2276, "60=^KC6^0=!LkX2Jg", "", options0, (-4243), (-2341), "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultNewLine = "";
      helpFormatter0.defaultWidth = (-1202);
      helpFormatter0.defaultArgName = "";
      helpFormatter0.defaultOptPrefix = "}=Nc\"H`<(1";
      helpFormatter0.rtrim("");
      helpFormatter0.setLongOptSeparator("BMw[pv");
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp("}=Nc\"H`<(1", options0, false);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test98()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer(74);
      stringBuffer0.codePoints();
      Options options0 = new Options();
      options0.hasOption("-");
      helpFormatter0.renderOptions(stringBuffer0, 0, options0, 1170, 0);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      helpFormatter1.defaultSyntaxPrefix = "usage: ";
      helpFormatter0.setDescPadding(0);
      String string0 = "?ZfO2u";
      Options options1 = new Options();
      // Undeclared exception!
      helpFormatter0.printHelp(1, " ", "usage: ", options1, "a@:i[91|&P@D", false);
  }
}
