/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 14 22:07:48 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      Option option0 = option_Builder0.get();
      option0.setArgs((-94));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-94), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option((String) null, false, "?+|ioF&(ft");
      option0.setArgs((-2361));
      // Undeclared exception!
      try { 
        option0.processValue("r(0S47}:E");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option option0 = new Option("$2K", "$2K", true, "Cidbi$qhQM-Xgu7h");
      option0.setOptionalArg(true);
      option0.setArgs(0);
      option0.processValue("$2K");
      assertEquals(0, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.numberOfArgs((-2384));
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('g');
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated((DeprecatedAttributes) null);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.isValuesEmpty();
      assertTrue(option0.hasLongOpt());
      assertEquals(" since ", option0.getDescription());
      assertEquals("lVyd6qoum", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.processValue("");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasLongOpt());
      assertFalse(boolean0);
      assertEquals(" since ", option0.getDescription());
      assertEquals(108, option0.getId());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setOptionalArg(true);
      boolean boolean0 = option0.hasOptionalArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.processValue("");
      option0.getValuesList();
      assertEquals(" since ", option0.getDescription());
      assertFalse(option0.hasValueSeparator());
      assertEquals("lVyd6qoum", option0.getLongOpt());
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option("Cidbi$qhQM-Xgu7h", "org.apache.commons.cli.Util");
      option0.setValueSeparator('0');
      char char0 = option0.getValueSeparator();
      assertEquals('0', char0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setValueSeparator('O');
      char char0 = option0.getValueSeparator();
      assertEquals('O', char0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "&|SZzHQ#vjm|w");
      option0.getValue((String) null);
      assertEquals("&|SZzHQ#vjm|w", option0.getDescription());
      assertTrue(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.processValue("");
      String string0 = option0.getValue((String) null);
      assertTrue(option0.hasLongOpt());
      assertEquals("lVyd6qoum", option0.getLongOpt());
      assertEquals(" since ", option0.getDescription());
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setValueSeparator('O');
      option0.setArgs(1101);
      option0.processValue("Option ");
      option0.getValue();
      assertEquals(1101, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      option_Builder0.since("Z");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      option_Builder0.since("");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.getOpt();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option((String) null, "oy=#ILnd]>O/q@BA", false, "oy=#ILnd]>O/q@BA");
      String string0 = option0.getLongOpt();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      String string0 = option0.getDescription();
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("converterMap");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt(")F/)otp@, ,w*l<v");
      Option option0 = option_Builder0.get();
      assertEquals((-1), option0.getArgs());
      
      option0.setArgs(0);
      int int0 = option0.getArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      int int0 = option0.getArgs();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.argName(")F/)otp@, ,w*l<v");
      option_Builder0.longOpt(")F/)otp@, ,w*l<v");
      Option option0 = option_Builder1.get();
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      option0.setArgName("");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option("O2RYMC", "\"", true, "\"");
      // Undeclared exception!
      try { 
        option0.setType((Object) "02Z$6\"WfnDyLs22");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      option0.setArgs(2051);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.processValue("org.apache.commons.cli.Option");
      try { 
        option0.getValue(45);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 45, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("2tE>B`");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option '2tE>B`' contains an illegal character : '>'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", true, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "", true, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("org.apache.commons.cli.Option$1", "org.apache.commons.cli.Option$1");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.Option$1' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = new Option("$2K", "$2K", true, "Cidbi$qhQM-Xgu7h");
      option0.isDeprecated();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("$2K", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "&|SZzHQ#vjm|w");
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals("&|SZzHQ#vjm|w", option0.getDescription());
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertEquals("", option0.getKey());
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setValueSeparator('O');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('O', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("y");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArgs();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setArgs(1101);
      boolean boolean0 = option0.hasArgs();
      assertEquals(1101, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArg();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.hasArg();
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option("$2K", "$2K", true, "Cidbi$qhQM-Xgu7h");
      option0.setArgs(0);
      boolean boolean0 = option0.hasArg();
      assertEquals(0, option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      Option option0 = option_Builder0.get();
      option0.getValue();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.processValue("org.apache.commons.cli.Util");
      String string0 = option0.getValue();
      assertFalse(option0.hasValueSeparator());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      String string0 = option0.getKey();
      assertEquals((-1), option0.getArgs());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.getValueSeparator();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      Class<Integer> class0 = Integer.class;
      option0.setType(class0);
      assertTrue(option0.hasLongOpt());
      assertEquals(" since ", option0.getDescription());
      assertEquals("lVyd6qoum", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String string0 = option0.toString();
      assertEquals("[ Option null [ARG] :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("[ARG...]");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toString();
      assertEquals("[ Option null [ARG...] Deprecated :: null :: class java.lang.String ]", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("convPterp");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'convPterp': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("[ARG...]");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'null''[ARG...]': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, "lVyd6qoum");
      option0.processValue("lVyd6qoum");
      option0.setArgs((-2));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, "lVyd6qoum");
      option0.setArgs((-2));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setValueSeparator('O');
      option0.processValue("Option ");
      assertEquals('O', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "&|SZzHQ#vjm|w");
      // Undeclared exception!
      try { 
        option0.processValue("k2&)+q_8{z3hgk#");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("[ARG...]");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isDeprecated();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      boolean boolean0 = option0.hasLongOpt();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertTrue(boolean0);
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      boolean boolean0 = option0.hasLongOpt();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.longOpt("Y=B-Fw5uTW|I-Pq");
      Option.Builder option_Builder2 = option_Builder1.hasArgs();
      Option option0 = option_Builder2.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.setArgName(" since ");
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, "lVyd6qoum");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, "lVyd6qoum");
      option0.setArgs((-2));
      option0.processValue("");
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      String[] stringArray0 = option0.getValues();
      assertTrue(option0.hasLongOpt());
      assertNull(stringArray0);
      assertEquals(" since ", option0.getDescription());
      assertEquals("lVyd6qoum", option0.getKey());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      assertTrue(option0.hasArg());
      
      option0.processValue("org.apache.commons.cli.Util");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, "lVyd6qoum");
      option0.getValue((-2));
      assertTrue(option0.hasLongOpt());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      option0.processValue("");
      try { 
        option0.getValue((-2));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      String string0 = option0.getValue("lVyd6qoum");
      assertEquals(" since ", option0.getDescription());
      assertEquals(1, option0.getArgs());
      assertEquals("lVyd6qoum", option0.getLongOpt());
      assertTrue(option0.hasLongOpt());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      Option option0 = option_Builder0.get();
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertEquals(1, option0.getArgs());
      assertNotNull(converter1);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      Option option1 = new Option("lVyd6qoum", true, " since ");
      boolean boolean0 = option0.equals(option1);
      assertEquals(" since ", option1.getDescription());
      assertFalse(option1.hasLongOpt());
      assertEquals(" since ", option0.getDescription());
      assertEquals(1, option1.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      Option option1 = (Option)option0.clone();
      boolean boolean0 = option0.equals(option1);
      assertEquals((-1), option1.getArgs());
      assertFalse(option1.hasLongOpt());
      assertTrue(boolean0);
      assertNotSame(option1, option0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      boolean boolean0 = option0.equals(option0);
      assertTrue(boolean0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.equals((Object) null);
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option option0 = new Option("$2uK", "$2uK", true, "$2uK");
      option0.processValue("$2uK");
      // Undeclared exception!
      try { 
        option0.processValue("$2uK");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.acceptsArg();
      assertTrue(option0.hasOptionalArg());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "&|SZzHQ#vjm|w");
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasLongOpt());
      assertEquals("&|SZzHQ#vjm|w", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
      assertEquals("", option0.getKey());
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("convPterp");
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      assertTrue(option0.hasLongOpt());
      
      option0.setLongOpt((String) null);
      Option option1 = new Option("lVyd6qoum", true, " since ");
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option option0 = new Option("e", "e");
      option0.getType();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.longOpt("Y=B-Fw5uTW|I-Pq");
      Option option0 = option_Builder1.get();
      // Undeclared exception!
      try { 
        option0.addValue("Not yet implemented");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("Z");
      Option option0 = option_Builder0.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option("e", "e");
      option0.hashCode();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.isRequired();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option("converterMap", "converterMap");
      option0.getSince();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option((String) null, "lVyd6qoum", true, " since ");
      String string0 = option0.getDescription();
      assertEquals(" since ", string0);
      assertTrue(option0.hasArg());
      assertNotNull(string0);
      assertTrue(option0.hasLongOpt());
      assertEquals(108, option0.getId());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      int int0 = option0.getArgs();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.clearValues();
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals(1, option0.getArgs());
      assertEquals("$2K", option0.getOpt());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.getDeprecated();
      assertEquals(1, option0.getArgs());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("$2K", option0.getOpt());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.hasOptionalArg();
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals(1, option0.getArgs());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("$2K", option0.getKey());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      
      option0.setDescription("Cidbi$qhQM-Xgu7h");
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("$2K", option0.getKey());
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.getValuesList();
      assertEquals(1, option0.getArgs());
      assertEquals("Cidbi$qhQM-Xgu7h", option0.getDescription());
      assertEquals("org.apache.commons.cli.Util", option0.getLongOpt());
      assertEquals("$2K", option0.getKey());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setArgs(1101);
      option0.toString();
      assertEquals(1101, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setRequired(true);
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasOptionalArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option option0 = new Option("$2K", "org.apache.commons.cli.Util", true, "Cidbi$qhQM-Xgu7h");
      option0.setValueSeparator('O');
      option0.processValue("$2K");
      // Undeclared exception!
      try { 
        option0.processValue("Option ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Class<Object> class0 = Object.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArgs();
      option_Builder0.longOpt("[ARG...]");
      Option option0 = option_Builder0.get();
      option0.processValue("~B`E1Ed");
      String string0 = option0.getValue(0);
      assertFalse(option0.hasValueSeparator());
      assertNotNull(string0);
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("convPterp");
      Option.Builder option_Builder1 = option_Builder0.desc("Option 'convPterp': Deprecated");
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("convPterp");
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      assertSame(option_Builder0, option_Builder2);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("y");
      Option option0 = option_Builder0.get();
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      option_Builder0.converter(converter0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required();
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      option_Builder0.longOpt("Y=B-Fw5uTW|I-Pq");
      Option option0 = option_Builder0.get();
      int int0 = option0.getId();
      assertEquals((-1), option0.getArgs());
      assertEquals(89, int0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      assertSame(option_Builder1, option_Builder0);
  }
}
