/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 14 22:27:56 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", arrayList0, vector0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("e9-jX", vector0, (List<String>) null, treeSet0);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedHashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, vector1, arrayDeque0);
      List<String> list0 = tableDefinition0.headers();
      assertFalse(arrayDeque0.contains(list0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedHashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, vector1, arrayDeque0);
      vector1.add((String) null);
      List<String> list0 = tableDefinition0.headers();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedHashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, (List<TextStyle>) null, vector0, arrayDeque0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedHashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, vector1, arrayDeque0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>(549);
      ArrayList<String> arrayList1 = new ArrayList<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, arrayList0, arrayList1, hashSet0);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("+", arrayList0, (List<String>) null, linkedHashSet0);
      String string0 = tableDefinition0.caption();
      assertEquals("+", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }
}
